Email sent successfully!
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/Half_Earthaug17Batch/0.42727272727272725'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/Half_Earthaug17Batch/0.49460874432487006'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/Half_Earthaug17Batch/0.4636363636363636'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simAUBatch.py", line 663, in <module>
    masslist_txt_append(simAU_masses,f'Masslists/{presentDirectory}{CLargs.date}Batch.txt','simAU','a', leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 223, in masslist_txt_append
    masslist_txt_append(masslist, filepath, sim, write_type, leaveGithub = False) # Using all the same parameters except setting recursion to False.
  File "simAUBatch.py", line 212, in masslist_txt_append
    file.write(message)
OSError: [Errno 122] Disk quota exceeded
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simAUBatch.py", line 663, in <module>
    masslist_txt_append(simAU_masses,f'Masslists/{presentDirectory}{CLargs.date}Batch.txt','simAU','a', leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 223, in masslist_txt_append
    masslist_txt_append(masslist, filepath, sim, write_type, leaveGithub = False) # Using all the same parameters except setting recursion to False.
  File "simAUBatch.py", line 212, in masslist_txt_append
    file.write(message)
OSError: [Errno 122] Disk quota exceeded
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
OSError: [Errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "massListSorter.py", line 52, in <module>
    massListSorter(sys.argv[2])
  File "massListSorter.py", line 30, in massListSorter
    file.write('\n')
OSError: [Errno 122] Disk quota exceeded
date: 
