Email sent successfully!
/N/u/taylor11/Carbonate/.local/lib/python3.7/site-packages/rebound/simulation.py:719: RuntimeWarning: At least 10 predictor corrector loops in IAS15 did not converge. This is typically an indication of the timestep being too large.
  warnings.warn(msg[1:], RuntimeWarning)
Traceback (most recent call last):
  File "simAUBatchsept13.py", line 672, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatchsept13.py", line 330, in saveFigs
    particleNumber=particleNumber, asteroidAU=asteroidAU, asteroidEccs=asteroidEccs, asteroidX=asteroidX, asteroidY=asteroidY)
  File "/N/soft/rhel7/anaconda/python3.7/2019.03/lib/python3.7/site-packages/numpy/lib/npyio.py", line 619, in savez
    _savez(file, args, kwds, False)
  File "/N/soft/rhel7/anaconda/python3.7/2019.03/lib/python3.7/site-packages/numpy/lib/npyio.py", line 728, in _savez
    pickle_kwargs=pickle_kwargs)
  File "/N/soft/rhel7/anaconda/python3.7/2019.03/lib/python3.7/site-packages/numpy/lib/format.py", line 645, in write_array
    fp.write(chunk.tobytes('C'))
  File "/N/soft/rhel7/anaconda/python3.7/2019.03/lib/python3.7/zipfile.py", line 1098, in write
    self._fileobj.write(data)
OSError: [Errno 122] Disk quota exceeded
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Email sent successfully!
Tue Oct 26 21:08:50 EDT 2021
