Email sent successfully!
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/9.8_SuperEarthaug17Batch/0.3747474747474747'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/9.8_SuperEarthaug17Batch/0.3343434343434344'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/9.8_SuperEarthaug17Batch/0.3909090909090909'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/9.8_SuperEarthaug17Batch/0.40303030303030307'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/9.8_SuperEarthaug17Batch/0.36262626262626263'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Traceback (most recent call last):
  File "simAUBatch.py", line 666, in <module>
    saveFigs(innerFolder= f"{presentDirectory}{CLargs.date}Batch", distance = distance, addOn = f"_{distance}",leaveGithub = "Rebound", leaveEnd = f"{CLargs.date}/{presentDirectory}")
  File "simAUBatch.py", line 323, in saveFigs
    os.mkdir("Figures/"+innerFolder+str(distance))
OSError: [Errno 122] Disk quota exceeded: 'Figures/9.8_SuperEarthaug17Batch/0.38282828282828285'
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 122] Disk quota exceeded
Fri Aug 27 01:14:57 EDT 2021
